config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users

  resources :instruments, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    # as musician
    resources :reservations, only: [:new, :create]
  end

  resource :profile, only: [:show, :edit, :update]

  # as owner
  resources :demands, only: [] do
    member do
      patch :accept
      patch :refuse
    end
  end

  get 'styleguide', to: 'pages#styleguide'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  CATEGORIES = ['Guitare', "Violon", "Piano", "Trompette", "Batterie", "Cor De Chasse"]

  belongs_to :user
  has_many :reservations

  validates :city, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORIES }
  validates :name, presence: true, length: { maximum: 60 }
  validates :description, presence: true, length: { maximum: 600 }
  validates :price, presence: true


  geocoded_by :city
  after_validation :geocode, if: :will_save_change_to_city?


  # Cloudinary, photo upload
  mount_uploader :photo, PhotoUploader
end


# magratte = Instrument.create!(city: 'Nantes', category: 'Guitare', name: 'gibson', description: 'super gratte', price: 250, user_id: 2)


# Flat.near('Tour Eiffel', 10)

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :instrument

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :total_price, presence: true
  validates :status, presence: true, inclusion: { in: %w(pending accepted denied) }

  scope :pending, -> { where(status: 'pending') }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # As owner
  has_many :instruments
  has_many :demands, through: :instruments, source: :reservations

  # As renter
  has_many :reservations, dependent: :destroy

  # Cloudinary, avatar upload
  mount_uploader :avatar, PhotoUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/demands_controller.rb
class DemandsController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def accept
    @reservation = Reservation.find(params[:id])
    @reservation.status = "accepted"
    @reservation.save

    redirect_to profile_path
  end

  def refuse
    @reservation = Reservation.find(params[:id])
    @reservation.status = "refused"
    @reservation.save

    redirect_to profile_path
  end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index

    @category = params[:instrument][:category]
    @city     = params[:city]

    @instruments = Instrument.all

    @instruments = @instruments.where(category: @category) unless @category == ""
    @instruments = @instruments.where(city: @city) unless @city == ""

    @instruments = @instruments.where.not(latitude: nil, longitude: nil)

    @markers = @instruments.map do |instrument|
      {
        lat: instrument.latitude,
        lng: instrument.longitude#,
        # infoWindow: { content: render_to_string(partial: "/instruments/map_box", locals: { instrument: instrument }) }
      }
    end
  end

  def show
    @instrument = Instrument.find(params[:id])
  end

  def new
    @instrument = Instrument.new
  end

  def create
    @instrument = Instrument.new(instrument_params)
    @instrument.user = current_user

    if @instrument.save
      redirect_to profile_path
    else
      render :new
    end
  end

  def edit
    @instrument = Instrument.find(params[:id])
  end

  def update
    @instrument = Instrument.find(params[:id])

    if @instrument.update(instrument_params)
      redirect_to profile_path
    else
      render :edit
    end
  end

  def destroy
    @instrument = Instrument.find(params[:id])
    @instrument.destroy
    redirect_to profile_path
  end

  private

  def instrument_params
    params.require(:instrument).permit(
      :name,
      :category,
      :city,
      :price,
      :description,
      :photo
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @instruments = Instrument.all
    @last_instruments = Instrument.last(4)
  end

  def styleguide
  end


end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @instruments = current_user.instruments

    @pending_demands = current_user.demands.where(status: "pending")
    # binding.pry
    @accepted_demands = current_user.demands.where(status: "accepted")
    @reservations = current_user.reservations

  end
  
  def edit
    @profile = current_user
  end

  def update
    @profile = current_user

    if @profile.update(profile_params)
      redirect_to profile_path
    else
      render :edit
    end
  end

  private

  def profile_params
    params.require(:user).permit(
      :email,
      :first_name,
      :last_name,
      :phone_number,
      :avatar,
    )
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController


  def new
    @instrument  = Instrument.find(params[:instrument_id])
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservation_params_with_parsed_dates)

    @instrument             = Instrument.find(params[:instrument_id])
    @reservation.instrument = @instrument

    number_of_days = (@reservation.end_date - @reservation.start_date).to_i

    total_price = number_of_days * @instrument.price

    @reservation.total_price = total_price

    @reservation.user = current_user


    if @reservation.save
      redirect_to profile_path
    else
      render :new
    end

  end

  private

  def reservation_params_with_parsed_dates
    params                             = reservation_params
    start_date_string = params.delete(:start_date)
    end_date_string   = params.delete(:end_date)
    
    start_date = Date.strptime(start_date_string, "%m/%d/%Y")
    end_date   = Date.strptime(end_date_string, "%m/%d/%Y")


    params[:start_date] = start_date
    params[:end_date]   = end_date

    return params
  end

  def reservation_params
    params.require(:reservation).permit(:message, :start_date, :end_date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
 def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
   @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/instruments/edit.html.erb
<div class="container">
  <!-- <div style="margin-top: 200px"> -->
  <div class="row results">

      <%= simple_form_for @instrument, url: instrument_path do |f| %>
      <%= f.input :city, label: "Ville" %>
      <%= f.input :category, label: 'Catégorie', collection: Instrument::CATEGORIES, as: :select %>
      <%= f.input :description, label: "Description"%>
      <%= f.input :photo, label: "Photo" %>
      <!-- Preview photo  -->
      <div id="preview">
        <img src="http://saveabandonedbabies.org/wp-content/uploads/2015/08/default-300x169.png" alt>

        <script src="http://code.jquery.com/jquery-3.1.0.min.js"
        integrity="shaa256-cCueBR6CsyA4/9szpPfrX3s49M9vUU58gtiJj06wt/s="
        crossorigin="anonymous">
       </script>

       <script type="text/javascript">
        function readURL(input){
         if(input.files && input.files[0]){
          var reader = new FileReader();
          reader.onload = function(e){
           $('#preview img').attr('src', e.target.result);
          };
          reader.readAsDataURL(input.files[0]);
         }
        }
        $(document).on('change','input[type="file"]',function(){
         readURL(this);
        });
       </script>
      </div>
      <%= f.input :price, label: "Prix" %>
      <div>
      <%= f.submit 'Mise à jour', class: 'btn show-cta cta-input' %>
      </div>

      <% end %>
  </div>
</div>



<!-- t.bigint "user_id"
t.string "city"
t.string "category"
t.string "name"
t.text "description"
t.string "photo"
t.integer "price"
t.boolean "available", default: true
t.datetime "created_at", null: false
t.datetime "updated_at", null: false
t.float "latitude"
t.float "longitude"
t.index ["user_id"], name: "index_instruments_on_user_id"
 -->

app/views/instruments/index.html.erb
<div class="content">
  <div class="cards-container">
    <div class="row">
      <div class="col-xs-12" style="margin-top: 5vh;">
        <% if @category == "" && @city == "" %>
        <h2>L'instrument de vos rêves est peut être juste ici ...</h2>
        <% elsif @category == "" %>
        <h1>Trouvez votre bonheur à <%= @city %></h1>
        <% elsif @city == "" %>
        <h1>Et voilou pour les <%= @category %>s </h1>
        <% else %>
        <h1>Voici les <%= @category %> à <%= @city %></h1>
        <% end %>
      <div class="underline" style="margin-bottom: 3vh;"></div>
    </div>
<!-- 
    <div class="filter">
      <div class="col-xs-6 col-md-4 form-input">
        Du moins cher au plus cher
      </div>
      <div class="col-xs-6 col-md-4 form-input">
        Du plus cher au moins cher
      </div>
      <div class="col-xs-6 col-md-4 form-input">
        Filtrer par ville
      </div>
    </div> -->

    <% @instruments.each do |instrument| %>
      <div class="col-xs-12 col-sm-4 text-center">

        <div class="card">

          <% if instrument.photo.url.nil?%>
            <div class="card-image" style="background-image: url('assets/default-instrument.png')"></div>
          <% else %>
            <div class="card-image" style="background-image: url('<%=image_path instrument.photo%>')"></div>
          <% end %>

          <div class="card-description">
            <!-- User name -->
            <h6 class="card-user-name"><%= instrument.user.first_name %> <%= instrument.user.last_name %></h6>
            <!-- Name of annonce -->
            <h5 class="card-user-instrument"><%= link_to instrument.name, instrument_path(instrument) %></h5>
            <!-- Résumé de l'annonce peut-être mettre une limite de caractère -->
            <p class="card-resume"><%= truncate(instrument.description, length: 80) %></p>
          </div>



          <div class="card-footer">
            <div class="row">
              <div class="col-sm-2 card-price">
                  <!-- Price de l'annonce -->
                  <%= link_to instrument.price, instrument_path(instrument)%>€/jour
              </div>
            </div>
          </div>

            <!-- Image de l'utilisateur -->
          <% if instrument.user.avatar.nil? %>
            <%= image_tag('logo.png') %>
              <% else %>
                <%= cl_image_tag instrument.user.avatar, crop: :fill, class: "card-user" %>
              <% end %>
             <!-- <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay"> -->
             <%= link_to '', instrument_path(instrument), class: "card-link"  %>
            <!-- <a class="card-link" href="#" ></a> -->
          </div>
        </div>
      <% end %>
    </div>
  </div>

   <div id="map" data-markers="<%= @markers.to_json %>"></div>
  </div>

app/views/instruments/show.html.erb
<div class="container">

  <div class="row results full-height">
    <div class="col-xs-12 col-md-7 ">
      <div class="col-md-1 user-avatar">
        <%= cl_image_tag @instrument.user.avatar, height: 48, crop: :fill, class: 'avatar-pics' %>
      </div>
      <div class="col-md-4 user-info" style="margin-left: 20px ">
        <h4><%=@instrument.user.first_name %> <%= @instrument.user.last_name %></h4>
        <!-- <p>Inscrit le 12.08.2018</p> -->
        Inscrit le <%= @instrument.user.created_at.strftime('%m/%d/%Y') %>
      </div>

      <div class="underline" style="margin-top: 80px;"></div>
      <div class="col-xs-10 primary-text">
        <h2 class="primary-text"><%= @instrument.name %></h2>
      </div>
      <div class="col-xs-2 text-right">
        <h2 class="primary-text light"><%= @instrument.price %> €</h2>
      </div>
      <div class="underline" style="margin-top: 80px;"></div>

  
      <div class="col-md-12 description">
        <p> <%= @instrument.description%></p>
      </div>

    </div>

    <div class="col-xs-12 col-md-4 col-md-offset-1">
      <%= cl_image_tag @instrument.photo, height: 420, width: 320, crop: :fill, class: 'show-image' %>
      <%= link_to "Faire une demande", new_instrument_reservation_path(@instrument), class: "btn show-cta cta-input" %>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Müzik</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar'%>
    <%= render 'shared/flashes' %>
    
    <div id="modaldevise" class="modal fade">
      <%= render 'devise/shared/new' %>
    </div>

    <div id="modaldevise-sign" class="modal fade">
      <%= render 'devise/registrations/new' %>
    </div>
    
    <%= yield %>
    <%= render 'shared/footer'%>


    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js" %>
    <%= javascript_pack_tag "map" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-19deg, rgba(238,238,238,0.01) 0%, #D43F3F 100%), 
url(<%= image_path('homepage.jpg') %>);">

  <div class="banner-content">
    <h1>La müzik à portée de main</h1>
    <h3 style="margin-top: 5vh;">Louez ou proposez des instruments dans votre ville</h3>
    <form class="form-inline" style="margin-top: 6vh;" action="<%=instruments_path%>">
      <div class="form-group mb-2">
        <%= select("instrument", "category", Instrument::CATEGORIES, {include_blank: 'Choisissez un instrument'}) %>
      </div>
      <!-- ville -->
      <div class="form-group mx-sm-3 mb-2">
        <input type="text" class="form-control form-input text-input" name="city" placeholder="Tapez une ville">
      </div>
      <!-- Date -->
      <!--   <input type="text" class="form-control form-input text-input" placeholder="Début"> -->
      <div class="form-group mx-sm-3 mb-2">
        <input class="form-control form-input text-input" data-provide='datepicker' placeholder="Début">
      </div>

      <div class="form-group mx-sm-3 mb-2">
        <input class="form-control form-input text-input" data-provide='datepicker' placeholder="Fin">
      </div>
      <br>
      <button type="submit" class="btn mb-2 cta-home-search" style="margin-top: 5vh;">Rechercher</button>
  </form>

  </div>

</div>
<div class="container">
  <div class="row text-center section-home marged-top elements flex-center">
    <div class="col-md-4">

      <%= image_tag("Trouvez.png", width: "175", alt: "Edit Entry") %>
      <h2>Trouvez</h2>
      <div class="underline" style="margin-bottom: 2vh;"></div>
      <p class="home-text">Trouvez l'instrument qu'il vous faut, à deux pas de chez vous.</p>
    </div>

    <div class="col-md-4">
      <%= image_tag("Louez.png", width: "175", alt: "Edit Entry") %>
      <h2>Louez</h2>
      <div class="underline" style="margin-bottom: 2vh;"></div>
      <p class="home-text">Louez votre matériel en deux clics. Un jour, une semaine, un mois, à vous de choisir !</p>
    </div>

    <div class="col-md-4">
      <%= image_tag("Rencontrez.png", width: "175", alt: "Edit Entry") %>
      <h2>Rencontrez</h2>
      <div class="underline" style="margin-bottom: 2vh;"></div>
      <p class="home-text"> Rencontrez des musiciens, heureux de faire partager leur passion.</p>
    </div>
  </div>

</div>
  <div class="wrapper-home text-center">
    <div class="elements">
    <h2 class="home-text-shadow" style="margin-bottom: 3vh;">Déposez une annonce</h2>
    <h4 class="home-text-shadow" style="margin-bottom: 3vh;"> Et rejoignez une large communauté de musiciens</h4>
    <%= link_to t(".sign_up", default: "Pouêt-Pouêt"), '#', "data-toggle" => "modal", "data-target"=>"#modaldevise-sign", class:'btn cta-home'%>
  </div>
  </div>
 <div class="container">
  <div class="section-home">
    <div class="col-md-12">
      <h2 class= "text-center"> Les derniers instruments proposés</h2>
      <div class="underline" style="margin-bottom: 3vh;"></div>
    </div>

    <%  @last_instruments.each do |instrument| %>
      <div class="col-xs-12 col-sm-3 text-center">
        <div class="card">
           <% if instrument.photo.url.nil?%>
            <div class="card-image" style="background-image: url('assets/default-instrument.png')"></div>
          <% else %>
            <div class="card-image" style="background-image: url('<%=image_path instrument.photo%>')"></div>
          <% end %>
          <div class="card-description">

            <!-- User name -->
            <h6 class="card-user-name"><%= instrument.user.first_name %> <%= instrument.user.last_name %></h6>
            <!-- Name of annonce -->
            <h5 class="card-user-instrument"><%= link_to instrument.name, instrument_path(instrument) %></h5>
            <!-- Résumé de l'annonce peut-être mettre une limite de caractère -->
            <p class="card-resume"><%= truncate(instrument.description, length: 80) %></p>

          </div>

          <div class="card-footer">
            <div class="row">
              <div class="col-sm-2 card-price">
                  <!-- Price de l'annonce -->
                  <%= link_to instrument.price, instrument_path(instrument)%>€/jour

              </div>
                </div>
              </div>

            <!-- Image de l'utilisateur -->
            <% if instrument.user.avatar.nil? %>
                  <%= image_tag('logo.png') %>
                <% else %>
                  <%= cl_image_tag instrument.user.avatar, crop: :fill, class: "card-user" %>
                <% end %>
             <!-- <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay"> -->
             <%= link_to '', instrument_path(instrument), class: "card-link"  %>
            <!-- <a class="card-link" href="#" ></a> -->
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="wrapper-home text-center">
    <div class="elements">
      <div class="col-md-4">
        <h2 class="home-text-shadow">Anatroll Gonon</h2>
        <p class="home-text-shadow">Expert en xylophone depuis 1998</p>
      </div>

      <div class="col-md-4">
        <h2 class="home-text-shadow">Harday Taskar</h2>
        <p class="home-text-shadow">Sa passion? La flûte de pan</p>
      </div>

      <div class="col-md-4">
        <h2 class="home-text-shadow">JJ Bernardo</h2>
        <p class="home-text-shadow"> Grand prix de Triangle en 1979 à Berlin </p>
      </div>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="container">

  <div class="row results">
    <!-- <h2>Reservations on my instruments</h2> -->
   <% @pending_demands.each do |demand| %>
    <li class="list-unstyled" style="margin-bottom: 8vh;">
      <div class="col-md-1 user-avatar text-center">
        <%= cl_image_tag demand.user.avatar, height: 48, crop: :fill, class: 'avatar-pics' %>  
      </div>
      <div class="col-md-9">
      <h2><%= demand.user.first_name %> veut louer votre <%= demand.instrument.name %></h2>
      Du <%= demand.start_date %> au <%= demand.end_date %> à <%= demand.total_price %>€ 
      </div>
      <div class="button-container" style="display:flex;">
      <%= link_to 'Accepter', accept_demand_path(demand), method: 'patch', class: ' show-cta', style: 'width:150px; color:#FFF;'%>
      <%= link_to 'Refuser', refuse_demand_path(demand), method: 'patch', class: 'primary-text show-cta-outline', style: 'width:150px;' %>
      </div>
    </li>
   <% end %>



    <div class="col-xs-12 col-md-12 ">
      <div class="col-md-1">
          <%= cl_image_tag current_user.avatar, height: 48, width: 48, crop: :fill, class: "avatar-pics" %>
      </div>
      <div class="col-md-9 user-info" style="margin-left: 20px">
        <h4 class="primary-text"><%=current_user.first_name %> <%= current_user.last_name %></h4>
        <p>Inscrit le 12.08.2018</p>
      </div>
      <div class="col-md-1 user-info" >
        <p class="text-right"><%=current_user.email%></p>
        <p class="text-right"><%=current_user.phone_number%></p>
      </div>
      <div class="underline" style="margin-top: 80px;"></div>

      <div class="instruments" style="margin-top: 24px;"></div>
      <h2 style="margin-bottom: 40px;">Mes instruments en location</h2>
      <% @instruments.each do |instrument| %>

      <div class="col-xs-12 col-sm-3 text-center">
      <div class="card">

        <% if instrument.photo.url.nil?%>
          <div class="card-image" style="background-image: url('assets/default-instrument.png')"></div>
        <% else %>
          <div class="card-image" style="background-image: url('<%=image_path instrument.photo%>')"></div>
        <% end %>
        <div class="card-description">
            <!-- User name -->
            <h6 class="card-user-name"><%= current_user.first_name %> <%= current_user.last_name %></h6>
            <!-- Name of annonce -->
            <h5 class="card-user-instrument"><%= instrument.name %></h5>
            <!-- Résumé de l'annonce peut-être mettre une limite de caractère -->
            <p class="card-resume"><%= truncate(instrument.description, length: 80) %></p>

          </div>

          <div class="card-footer">
            <div class="row">
              <div class="col-sm-6 card-price">
                  <%= link_to " Modifier", edit_instrument_path(instrument)%>
              </div>
              <div class="col-sm-6 card-price">
                  <%= link_to 'Supprimer',instrument_path(instrument), method: :delete, data: { confirm: "Vous êtes sur ?" } %>
              </div>
            </div>
          </div>

        </div>
      </div>
    <% end %>
  </div>
</div>
  <div class="row results">
    <div class="col-xs-6">
       <h2 class="text-center">J'ai prété</h2>
       <div class="underline" style="margin-bottom: 2vh"></div>
        <% @accepted_demands.each do |demand| %>
          <div class="col-md-2">
            <%= cl_image_tag demand.user.avatar, height: 48, width: 48, crop: :fill, class: "avatar-pics" %>
          </div>

          <div class="col-md-10">
            <h4><%= demand.user.first_name %> a loué votre <%= demand.instrument.name %></h4>
            <p>Du <%= demand.start_date %> au <%= demand.end_date %> pour <%= demand.total_price %>€</p>
          </div>
    <% end %>
    </div>

    <div class="row">
      <div class="col-xs-6">
        <h2 class="text-center">J'ai emprunté</h2>
        <div class="underline" style="margin-bottom: 2vh"></div>
        <% @reservations.each do |reservation| %>
          <div class="col-md-2">
            <%= cl_image_tag reservation.instrument.user.avatar, height: 48, width: 48, crop: :fill, class: "avatar-pics" %>
          </div>

          <div class="col-md-10">
            <h4> Vous avez <%= reservation.instrument.name %> à <%= reservation.instrument.user.first_name %></h4>
            <p>Du <%= reservation.start_date %> au <%= reservation.end_date %> pour <%= reservation.total_price %>€</p>
          </div>
          <% end %>
        </div>
      </div>
    </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert" style = "margin-top: 70px">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert"  style = "margin-top: 70px">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>


<!--
<script type="text/javascript">

$(document).ready(function(){
  setTimeout(function(){
    $('.alert').remove();
  }, 5);
 })
</script>
 -->

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 35 %>
  <% end %>



  <!-- Central Navigation -->

  <% if params[:controller] == "pages" && params[:action] == "home" %>
  
  <% else %>
    <form class="form-inline" action="<%= instruments_path %>">
      <%= select("instrument", "category", Instrument::CATEGORIES, {include_blank: 'Choisissez un instrument'}) %>
      <div class="form-group mx-sm-3 mb-2">
        <input type="text" class="form-control form-input text-input" name="city" placeholder="Tapez une ville">
      </div>
      <button type="submit" class="btn btn-primary mb-2 form-input-primary text-input-primary">Rechercher</button>
    </form>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Ajouter un instrument", new_instrument_path, class: "navbar-wagon-item navbar-wagon-link text-input" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% pending_reservations_count = current_user.demands.pending.count %>
          <% if pending_reservations_count >= 1 %>
            <div class="notification text-center"><%= pending_reservations_count %></div>  
          <% end %>
        
          <% if current_user.avatar.url.nil?%>
           <%= image_tag("default-user.png", class: "avatar dropdown-toggle", "data-toggle" => "dropdown") %>
          <% else %>
          <%= cl_image_tag current_user.avatar, height: 48, width: 48, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to profile_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Mon profil") %>
              <% end %>
            </li>
            <li>
              <%= link_to edit_profile_path do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Paramètres") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Me déconnecter") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_up", default: "Signup"), '#', "data-toggle" => "modal", "data-target"=>"#modaldevise-sign", class: "navbar-wagon-item navbar-wagon-link" %>


      <%= link_to t(".sign_in", default: "Login"), '#', "data-toggle" => "modal", "data-target"=>"#modaldevise", class: "navbar-wagon-item navbar-wagon-link text-cta" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>